.TH GW_DATA_FIND "1" "2023\-12\-18" "gwdatafind 1.2.0" "Generated Python Manual"
.SH NAME
gw_data_find \- discover available GW data
.SH SYNOPSIS
.B gw_data_find
[-h] [-V] [[-p | -w | -y | -a | -f FILE | -T]] [-o OBS] [-t TYPE] [-s GPS] [-e GPS] [-x EXT] -r HOST [-P] [[-l | -W | -n]] [-m MATCH] [-u URL_TYPE] [-g] [-O PATH]
.SH DESCRIPTION
Query a GWDataFind server for information.

.SH OPTIONAL ARGUMENTS
.TP
\fB\-V\fR, \fB\-\-version\fR
show version number and exit

.SH QUERY TYPES
Select one of the following, if none are selected a query for frame URLS will be performed

.TP
\fB\-p\fR, \fB\-\-ping\fR
ping the DataFind server

.TP
\fB\-w\fR, \fB\-\-show\-observatories\fR
list available observatories

.TP
\fB\-y\fR, \fB\-\-show\-types\fR
list available file types

.TP
\fB\-a\fR, \fB\-\-show\-times\fR
list available segments

.TP
\fB\-f\fR \fI\,FILE\/\fR, \fB\-\-filename\fR \fI\,FILE\/\fR
resolve URL(s) for a particular file name

.TP
\fB\-T\fR, \fB\-\-latest\fR
resolve URL(s) for the most recent file of the specified type

.SH DATA OPTIONS
Parameters for your query. Which options are required depends on the query type

.TP
\fB\-o\fR \fI\,OBS\/\fR, \fB\-\-observatory\fR \fI\,OBS\/\fR
observatory(ies) that generated frame file; use \-\-show\-observatories to see what is available.

.TP
\fB\-t\fR \fI\,TYPE\/\fR, \fB\-\-type\fR \fI\,TYPE\/\fR
type of frame file, use \-\-show\-types to see what is available.

.TP
\fB\-s\fR \fI\,GPS\/\fR, \fB\-\-gps\-start\-time\fR \fI\,GPS\/\fR
start of GPS time search

.TP
\fB\-e\fR \fI\,GPS\/\fR, \fB\-\-gps\-end\-time\fR \fI\,GPS\/\fR
end of GPS time search

.TP
\fB\-x\fR \fI\,EXT\/\fR, \fB\-\-extension\fR \fI\,EXT\/\fR
file extension for which to search

.SH CONNECTION OPTIONS
Authentication and connection options.

.TP
\fB\-r\fR \fI\,HOST\/\fR, \fB\-\-server\fR \fI\,HOST\/\fR
hostname and optional port of server to query

.TP
\fB\-P\fR, \fB\-\-no\-proxy\fR
attempt to authenticate without a grid proxy

.SH OUTPUT OPTIONS
Parameters for parsing and writing output.

.TP
\fB\-l\fR, \fB\-\-lal\-cache\fR
format output for use as a LAL cache file

.TP
\fB\-W\fR, \fB\-\-frame\-cache\fR
format output for use as a frame cache file

.TP
\fB\-n\fR, \fB\-\-names\-only\fR
display only the basename of each file

.TP
\fB\-m\fR \fI\,MATCH\/\fR, \fB\-\-match\fR \fI\,MATCH\/\fR
return only results that match a regular expression

.TP
\fB\-u\fR \fI\,URL_TYPE\/\fR, \fB\-\-url\-type\fR \fI\,URL_TYPE\/\fR
return only URLs with a particular scheme or head such as "file" or "gsiftp"

.TP
\fB\-g\fR, \fB\-\-gaps\fR
check the returned list of URLs or paths to see if the files cover the requested interval; a return value of zero (0) indicates the interval is covered, a value of one (1) indicates at least one gap exists and the interval is not , covered and a value of (2) indicates that the entire interval is not covered; missing gaps are printed to stderr

.TP
\fB\-O\fR \fI\,PATH\/\fR, \fB\-\-output\-file\fR \fI\,PATH\/\fR
path to output file, defaults to stdout
