
.TH nds2_channel_source 1 "November 24, 2013" "" "nds2_channel_source - show "

.SH NAME
nds2_channel_source \-  reports the times of the appropriate frames that should contain the channel data specified.

.SH SYNOPSIS
.B nds2_channel_source [-n <server>] [-p <port>]
           [-s <start-gps>] channel-list

.SH DESCRIPTION
This manual page explains the
.B nds2_channel_source
program. It uses the list of channels and the list frames that the NDS2 server maintains to report the times data 
.B should 
be available.  For performance reasons, each frame is not examined to confirm there are no gaps in the data.  So the data returned is informative but does not assure the Server has all the data for a particular request.

.SH OPTIONS
.B
.IP -OPTION

  where:
    -n      Specify server IP address
    -p      Specify port number [31200]
    -s      Specify start time (as GPS)
    -v      Verbose printout (dump channel data)
              <channel-list> Space delimited channel list

.SH "SEE ALSO"

Other programs in the NDS2 package are: nds-client-config, nds2_channel_source, nds_query, NDS2Frame

